extension Errno {
  public var errorNumber: Int32 {
    switch self {
    case .success:                                  return 0
    case .operationNotPermitted:                    return EPERM
    case .noSuchFileOrDirectory:                    return ENOENT
    case .noSuchProcess:                            return ESRCH
    case .interruptedSystemCall:                    return EINTR
    case .inputOutputError:                         return EIO
    case .deviceNotConfigured:                      return ENXIO
    case .argumentListTooLong:                      return E2BIG
    case .executableFormatError:                    return ENOEXEC
    case .badFileDescriptor:                        return EBADF
    case .noChildProcesses:                         return ECHILD
    case .resourceTemporarilyUnavailable:           return EAGAIN
    case .cannotAllocateMemory:                     return ENOMEM
    case .permissionDenied:                         return EACCES
    case .badAddress:                               return EFAULT
    case .blockDeviceRequired:                      return ENOTBLK
    case .deviceOrResourceBusy:                     return EBUSY
    case .fileExists:                               return EEXIST
    case .invalidCrossDeviceLink:                   return EXDEV
    case .noSuchDevice:                             return ENODEV
    case .notADirectory:                            return ENOTDIR
    case .isADirectory:                             return EISDIR
    case .invalidArgument:                          return EINVAL
    case .tooManyOpenFilesInSystem:                 return ENFILE
    case .tooManyOpenFiles:                         return EMFILE
    case .inappropriateInputOutputControlForDevice: return ENOTTY
    case .textFileBusy:                             return ETXTBSY
    case .fileTooLarge:                             return EFBIG
    case .noSpaceLeftOnDevice:                      return ENOSPC
    case .illegalSeek:                              return ESPIPE
    case .readOnlyFileSystem:                       return EROFS
    case .tooManyLinks:                             return EMLINK
    case .brokenPipe:                               return EPIPE
    case .numericalArgumentOutOfDomain:             return EDOM
    case .resultTooLarge:                           return ERANGE
    case .resourceDeadlockAvoided:                  return EDEADLK
    case .fileNameTooLong:                          return ENAMETOOLONG
    case .noLocksAvailable:                         return ENOLCK
    case .functionNotImplemented:                   return ENOSYS
    case .directoryNotEmpty:                        return ENOTEMPTY
    case .tooManyLevelsOfSymbolicLinks:             return ELOOP
    case .noMessageOfDesiredType:                   return ENOMSG
    case .identifierRemoved:                        return EIDRM
    case .channelNumberOutOfRange:                  return ECHRNG
    case .level2NotSynchronized:                    return EL2NSYNC
    case .level3Halted:                             return EL3HLT
    case .level3Reset:                              return EL3RST
    case .linkNumberOutOfRange:                     return ELNRNG
    case .protocolDriverNotAttached:                return EUNATCH
    case .noCSIStructureAvailable:                  return ENOCSI
    case .level2Halted:                             return EL2HLT
    case .invalidExchange:                          return EBADE
    case .invalidRequestDescriptor:                 return EBADR
    case .exchangeFull:                             return EXFULL
    case .noAnode:                                  return ENOANO
    case .invalidRequestCode:                       return EBADRQC
    case .invalidSlot:                              return EBADSLT
    case .badFontFileFormat:                        return EBFONT
    case .deviceNotAStream:                         return ENOSTR
    case .noDataAvailable:                          return ENODATA
    case .timerExpired:                             return ETIME
    case .outOfStreamsResources:                    return ENOSR
    case .machineIsNotOnTheNetwork:                 return ENONET
    case .packageNotInstalled:                      return ENOPKG
    case .objectIsRemote:                           return EREMOTE
    case .linkHasBeenSevered:                       return ENOLINK
    case .advertiseError:                           return EADV
    case .srmountError:                             return ESRMNT
    case .communicationErrorOnSend:                 return ECOMM
    case .protocolError:                            return EPROTO
    case .multihopAttempted:                        return EMULTIHOP
    case .rfsSpecificError:                         return EDOTDOT
    case .badMessage:                               return EBADMSG
    case .valueTooLargeForDefinedDataType:          return EOVERFLOW
    case .nameNotUniqueOnNetwork:                   return ENOTUNIQ
    case .fileDescriptorInBadState:                 return EBADFD
    case .remoteAddressChanged:                     return EREMCHG
    case .canNotAccessANeededSharedLibrary:         return ELIBACC
    case .accessingACorruptedSharedLibrary:         return ELIBBAD
    case .libSectionInAOutCorrupted:                return ELIBSCN
    case .attemptingToLinkInTooManySharedLibraries: return ELIBMAX
    case .cannotExecASharedLibraryDirectly:         return ELIBEXEC
    case .illegalByteSequence:                      return EILSEQ
    case .interruptedSystemCallShouldBeRestarted:   return ERESTART
    case .streamsPipeError:                         return ESTRPIPE
    case .tooManyUsers:                             return EUSERS
    case .socketOperationOnNonSocket:               return ENOTSOCK
    case .destinationAddressRequired:               return EDESTADDRREQ
    case .messageTooLong:                           return EMSGSIZE
    case .protocolWrongTypeForSocket:               return EPROTOTYPE
    case .protocolNotAvailable:                     return ENOPROTOOPT
    case .protocolNotSupported:                     return EPROTONOSUPPORT
    case .socketTypeNotSupported:                   return ESOCKTNOSUPPORT
    case .operationNotSupported:                    return EOPNOTSUPP
    case .protocolFamilyNotSupported:               return EPFNOSUPPORT
    case .addressFamilyNotSupportedByProtocol:      return EAFNOSUPPORT
    case .addressAlreadyInUse:                      return EADDRINUSE
    case .cannotAssignRequestedAddress:             return EADDRNOTAVAIL
    case .networkIsDown:                            return ENETDOWN
    case .networkIsUnreachable:                     return ENETUNREACH
    case .networkDroppedConnectionOnReset:          return ENETRESET
    case .softwareCausedConnectionAbort:            return ECONNABORTED
    case .connectionResetByPeer:                    return ECONNRESET
    case .noBufferSpaceAvailable:                   return ENOBUFS
    case .socketIsAlreadyConnected:                 return EISCONN
    case .socketIsNotConnected:                     return ENOTCONN
    case .cannotSendAfterSocketShutdown:            return ESHUTDOWN
    case .tooManyReferences:                        return ETOOMANYREFS
    case .connectionTimedOut:                       return ETIMEDOUT
    case .connectionRefused:                        return ECONNREFUSED
    case .hostIsDown:                               return EHOSTDOWN
    case .noRouteToHost:                            return EHOSTUNREACH
    case .operationAlreadyInProgress:               return EALREADY
    case .operationNowInProgress:                   return EINPROGRESS
    case .staleFileHandle:                          return ESTALE
    case .structureNeedsCleaning:                   return EUCLEAN
    case .notAXENIXNamedTypeFile:                   return ENOTNAM
    case .noXENIXSemaphoresAvailable:               return ENAVAIL
    case .isANamedTypeFile:                         return EISNAM
    case .remoteIOError:                            return EREMOTEIO
    case .diskQuotaExceeded:                        return EDQUOT
    case .noMediumFound:                            return ENOMEDIUM
    case .wrongMediumType:                          return EMEDIUMTYPE
    case .operationCanceled:                        return ECANCELED
    case .requiredKeyNotAvailable:                  return ENOKEY
    case .keyHasExpired:                            return EKEYEXPIRED
    case .keyHasBeenRevoked:                        return EKEYREVOKED
    case .keyWasRejectedByService:                  return EKEYREJECTED
    case .previousOwnerDied:                        return EOWNERDEAD
    case .stateNotRecoverable:                      return ENOTRECOVERABLE
    case .undefind(let errorNumber):                return errorNumber
    }
  }
}